per_question_time: 48000
first_question_delay: 1200

questions:
  [
    [ "MC游戏世界中 ，一天的时间换算成现实时间是多少分钟？","20" ],
    [ "我的世界中一共有多少种玻璃?","17" ],
    [ "在日常烧物品的时候，一个煤炭可供几个物品燃烧?","8" ],
    [ "我的世界中一共有多少种染料?","16" ],
    [ "在本版本中主世界生物群系有多少种？","53" ],
    [ "我的世界中唯一能作为光源和食物来源的物品是什么?","洞穴藤蔓" ],
    [ "木棍可以当做燃料，他能燃烧多少个物品?","0.5" ],
    [ "吃坤肉有百分之多少的概率会获得饥饿的效果?","30" ],
    [ "猪被闪电击中会变成什么?","僵尸猪人" ],
    [ "村民被闪电击中会变成什么?","女巫" ],
    [ "干草块可以减少百分之多少的摔落伤害?","80" ],
    [ "在IXBOB的服务器中烈焰棒的售价为多少?","1000" ],
    [ "对羊使用什么名字的命名牌会是羊变成彩色羊?","jeb_" ],
    [ "观察末影人的哪里会激怒它?","头部" ],
    [ "唤魔者会将半径16格以内的蓝色羊转化为什么颜色的羊?","红色" ],
    [ "治疗/转化僵尸村民会获得什么成就?","僵尸科医生" ],
    [ "在mc中，音符盒音色种类有多少?","16" ],
    [ "建立世界时对对游戏模式摁哪个键位可以改为调试模式?","Alt"],
    [ "在mc中，唱片有多少种?","15" ],
    [ "我的世界圣诞节彩蛋一般持续多少天?","3" ],
    [ "为致敬电影闪灵，卫道士有一种彩蛋命名牌，命名为?","Johnny" ],
    [ "蛋糕是个谎言成就来源于哪个游戏（该游戏制作公司也曾制作过求生之路系列）?","传送门" ],
    [ "用哪个物品和旗帜合成可以获得mojang旗帜?","附魔金苹果" ],
    [ "在以前版本中，第一次食用附魔金苹果会获得什么成就?","君临天下" ],
    [ "喷溅型药水往头顶丢时间获得Buff时间长还是往脚下丢?","头顶" ],
    [ "在没有任何护甲和buff情况下，玩家从多少格高度跳下正好保留半颗心?","22" ],
    [ "红色蘑菇牛被闪电劈中会变成什么颜色?","棕色" ]
  ]
must_rewards: [
    ["%vault_money%", "%amount%", 300]
  ]
probability_rewards: [
    [["%vault_money%", "%random_amount%", 100, 300], 0.8],
    [["iron_ingot", "%random_amount%", 1, 9], 0.5],
    [["diamond", "%random_amount%", 1, 5], 0.2],
    [["diamond_block", "%amount%", 1], 0.1],
    [["wither_skeleton_skull", "%amount%", 1], 0.05],
    [["nether_star", "%amount%", 1], 0.02],
    [["elytra", "%amount%", 1], 0.01],
    [["netherite_ingot", "%amount%", 1], 0.01]
  ]

