name: RewardQuestions
version: '1.0.0'
main: com.ixbob.rewardquestions.Main
api-version: '1.20'
author: 'IXBOB'
commands:
  quesreload:
    description: Reload the rewardquestion plugin.
    usage: /<command>
    permission: RewardQuestions.quesreload
    permission-message: You don't have permission <permission>!
